### ISSUE TITLE
CABLE: Update the Hive docs with the new Benchcab release

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#658] opened 2024-03-27 23:16 UTC
## Description
For the new release of the Benchcab, we might just create a new section under the `models` tab mentioning the new changes for the benchcab. 

## Why
For including the latest Benchcab instructions on the Hive docs.

## Close Criteria
- [ ] Discuss and include the updated benchcab documentation on the Hive.

**Comment by atteggiani** [comment] 2024-04-23 23:57
Is this a duplicate of #405?

**Closed** 2024-05-02 07:31 UTC
Labels: documentation
